[project]
name = "ai-implementations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu132"
